Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@wiltoninfra 
CodeViewDevops
/
ssm-api
0
0
0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
ssm-api
/
.github
/
workflows
/
main.yml
 

Spaces

2

No wrap
1
- name: Build and push Docker images
2
  # You may pin to the exact commit or the version.
3
  # uses: docker/build-push-action@0db984c1826869dcd0740ff26ff75ff543238fd9
4
  uses: docker/build-push-action@v2.2.1
5
  with:
6
    # Builder instance
7
    builder: # optional
8
    # Build's context is the set of files located in the specified PATH or URL
9
    context: # optional
10
    # Path to the Dockerfile
11
    file: # optional, default is ./Dockerfile
12
    # List of build-time variables
13
    build-args: # optional
14
    # List of metadata for an image
15
    labels: # optional
16
    # List of tags
17
    tags: # optional
18
    # Always attempt to pull a newer version of the image
19
    pull: # optional, default is false
20
    # Sets the target stage to build
21
    target: # optional
22
    # List of extra privileged entitlement (eg. network.host,security.insecure)
23
    allow: # optional
24
    # Do not use cache when building the image
25
    no-cache: # optional, default is false
26
    # List of target platforms for build
27
    platforms: # optional
28
    # Load is a shorthand for --output=type=docker
29
    load: # optional, default is false
30
    # Push is a shorthand for --output=type=registry
31
    push: # optional, default is false
32
    # List of output destinations (format: type=local,dest=path)
33
    outputs: # optional
34
    # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
35
    cache-from: # optional
36
    # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
37
    cache-to: # optional
38
    # List of secrets to expose to the build (eg. key=value, GIT_AUTH_TOKEN=mytoken)
39
    secrets: # optional
40
    # GitHub Token used to authenticate against a repository for Git context
41
    github-token: # optional, default is ${{ github.token }}
42
    # List of SSH agent socket or keys to expose to the build
43
    ssh: # optional≈
Use Control + Space to trigger autocomplete in most situations.
 /  / Build and push Docker images
Build and push Docker images
By docker 
 v2.2.1
 946
Build and push Docker images with Buildx

View full Marketplace listing
Installation
Copy and paste the following snippet into your .yml file.

Version: v2.2.1 
- name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@0db984c1826869dcd0740ff26ff75ff543238fd9
  uses: docker/build-push-action@v2.2.1
  with:
    # Builder instance
    builder: # optional
    # Build's context is the set of files located in the specified PATH or URL
    context: # optional
    # Path to the Dockerfile
    file: # optional, default is ./Dockerfile
    # List of build-time variables
    build-args: # optional
    # List of metadata for an image
    labels: # optional
    # List of tags
    tags: # optional
    # Always attempt to pull a newer version of the image
    pull: # optional, default is false
    # Sets the target stage to build
    target: # optional
    # List of extra privileged entitlement (eg. network.host,security.insecure)
    allow: # optional
    # Do not use cache when building the image
    no-cache: # optional, default is false
    # List of target platforms for build
    platforms: # optional
    # Load is a shorthand for --output=type=docker
    load: # optional, default is false
    # Push is a shorthand for --output=type=registry
    push: # optional, default is false
    # List of output destinations (format: type=local,dest=path)
    outputs: # optional
    # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
    cache-from: # optional
    # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
    cache-to: # optional
    # List of secrets to expose to the build (eg. key=value, GIT_AUTH_TOKEN=mytoken)
    secrets: # optional
    # GitHub Token used to authenticate against a repository for Git context
    github-token: # optional, default is ${{ github.token }}
    # List of SSH agent socket or keys to expose to the build
    ssh: # optional
